### ISSUE TITLE
dump_to_es fails

### ISSUE THREAD

**Issue by OriHoch** [OpenBudget/budgetkey-data-pipelines#113]
looks like there are changes in datapackage-pipelines-elasticsearch that need to be published?

```
budgetkey-data-pipelines$ budgetkey-dpp run ./budgetkey/elasticsearch/index_national_budget_changes
./budgetkey/elasticsearch/index_national_budget_changes: FAILURE, processed 0 rows
INFO    :RESULTS:
INFO    :FAILURE: ./budgetkey/elasticsearch/index_national_budget_changes 
ERROR log from processor dump_to_es:
+--------
| Traceback (most recent call last):
|   File "/home/ori/budgetkey-data-pipelines/datapackage_pipelines_budgetkey/processors/dump_to_es.py", line 59, in <module>
|     DumpToElasticSearch()()
|   File "/home/ori/budgetkey-data-pipelines/datapackage_pipelines_budgetkey/processors/dump_to_es.py", line 35, in __init__
|     'index.mapping.coerce': True
| TypeError: __init__() got an unexpected keyword argument 'index_settings'
+--------
```

**Comment by akariv** [comment]
https://github.com/frictionlessdata/datapackage-pipelines-elasticsearch/pull/1

we're using this branch atm until this pr is accepted

**Comment by akariv** [comment]
(see requirements-dev.txt)

**Comment by OriHoch** [comment]
thanks
