### ISSUE TITLE
[Data] [Scraper] Governmental and Ministerial Tenders

### ISSUE THREAD

**Issue by akariv** [OpenBudget/budgetkey-data-pipelines#40]
Generalise the exemption scraper to scrape these two sections in the procurement department:
- http://www.mr.gov.il/CentralTenders/Pages/SearchTenders.aspx
- http://www.mr.gov.il/OfficesTenders/Pages/SearchOfficeTenders.aspx
(notice the tabs in the first one)

The data from these pipelines should end up in the same table (unless the schemas are too different so that it doesn't make sense).

**Comment by OriHoch** [comment]
there is an error, investigating:
```
check_existing: /usr/local/lib/python3.6/site-packages/jsontableschema/model.py:48: UserWarning: Class models.SchemaModel is deprecated [v0.7-v1)
check_existing:   warnings.warn(message, UserWarning)
check_existing: INFO    :Found 0 central tender ids: []...
check_existing: INFO    :Found 0 office publication ids: []...
check_existing: INFO    :Found 64911 exemption publication ids: [596555, 596560, 595431, 594269, 585693, 586138, 586141, 585797, 585798, 585842, 585843, 567440, 567441, 550057, 550059, 550073, 550076, 550067, 547811, 547828]...
load_resource: /usr/local/lib/python3.6/site-packages/jsontableschema/model.py:48: UserWarning: Class models.SchemaModel is deprecated [v0.7-v1)
load_resource:   warnings.warn(message, UserWarning)
load_resource: INFO    :Processed 10244 rows
load_resource: /usr/local/lib/python3.6/site-packages/jsontableschema/model.py:48: UserWarning: Class models.SchemaModel is deprecated [v0.7-v1)
load_resource:   warnings.warn(message, UserWarning)
load_resource: INFO    :Processed 10365 rows
stream_remote_resources: /usr/local/lib/python3.6/site-packages/jsontableschema/model.py:48: UserWarning: Class models.SchemaModel is deprecated [v0.7-v1)
stream_remote_resources:   warnings.warn(message, UserWarning)
stream_remote_resources: INFO    :Processed 10365 rows
concatenate: /usr/local/lib/python3.6/site-packages/jsontableschema/model.py:48: UserWarning: Class models.SchemaModel is deprecated [v0.7-v1)
concatenate:   warnings.warn(message, UserWarning)
concatenate: INFO    :Processed 10365 rows
check_existing: INFO    :Processed 10365 rows
download_pages_data: /usr/local/lib/python3.6/site-packages/jsontableschema/model.py:48: UserWarning: Class models.SchemaModel is deprecated [v0.7-v1)
download_pages_data:   warnings.warn(message, UserWarning)
download_pages_data: DEBUG   :Starting new HTTP connection (1): www.mr.gov.il
download_pages_data: DEBUG   :http://www.mr.gov.il:80 "GET /officestenders/Pages/officetender.aspx?pID=556538 HTTP/1.1" 307 0
download_pages_data: DEBUG   :Starting new HTTPS connection (1): www.mr.gov.il
download_pages_data: DEBUG   :https://www.mr.gov.il:443 "GET /Pages/HomePage.aspx/officestenders/Pages/officetender.aspx?pID=556538 HTTP/1.1" 200 38042
download_pages_data: DEBUG   :Starting new HTTP connection (1): www.mr.gov.il
download_pages_data: DEBUG   :http://www.mr.gov.il:80 "GET /officestenders/Pages/officetender.aspx?pID=560731 HTTP/1.1" 307 0
download_pages_data: DEBUG   :Starting new HTTPS connection (1): www.mr.gov.il
parse_page_data: /usr/local/lib/python3.6/site-packages/jsontableschema/model.py:48: UserWarning: Class models.SchemaModel is deprecated [v0.7-v1)
parse_page_data:   warnings.warn(message, UserWarning)
parse_page_data: Traceback (most recent call last):
parse_page_data:   File "/budgetkey_data_pipelines/pipelines/procurement/tenders/parse_page_data.py", line 236, in 
parse_page_data:     ParsePageDataProcessor.main()
parse_page_data:   File "/budgetkey_data_pipelines/common/resource_filter_processor.py", line 54, in main
parse_page_data:     cls(ingest_response=ingest(), **kwargs).spew()
parse_page_data:   File "/budgetkey_data_pipelines/common/resource_filter_processor.py", line 47, in spew
parse_page_data:     spew(*self._get_spew_params())
parse_page_data:   File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/wrapper/wrapper.py", line 60, in spew
parse_page_data:     for rec in res:
parse_page_data:   File "/budgetkey_data_pipelines/pipelines/procurement/tenders/parse_page_data.py", line 102, in filter_resource_data
parse_page_data:     yield self.get_office_data(row, page, documents)
parse_page_data:   File "/budgetkey_data_pipelines/pipelines/procurement/tenders/parse_page_data.py", line 173, in get_office_data
parse_page_data:     "publication_id": int(source_data["publication_id"]),
parse_page_data: ValueError: invalid literal for int() with base 10: ''
download_pages_data: DEBUG   :https://www.mr.gov.il:443 "GET /Pages/HomePage.aspx/officestenders/Pages/officetender.aspx?pID=560731 HTTP/1.1" 200 37996
set_types: /usr/local/lib/python3.6/site-packages/jsontableschema/model.py:48: UserWarning: Class models.SchemaModel is deprecated [v0.7-v1)
set_types:   warnings.warn(message, UserWarning)
```

**Comment by OriHoch** [comment]
looks like this error occurs when IP is blocked, but the only way I could reproduce this block was by accessing from IP outside of israel

it was running via tzabar, so this shouldn't happen

**Comment by OriHoch** [comment]
the scraper-exemptions pipelines seems to be stuck in a loop:
```
add_publisher_urls_resource: DEBUG   :http://www.mr.gov.il:80 "POST /ExemptionMessage/Pages/SearchExemptionMessages.aspx HTTP/1.1" 307 0
add_publisher_urls_resource: DEBUG   :https://www.mr.gov.il:443 "POST /ExemptionMessage/Pages/SearchExemptionMessages.aspx HTTP/1.1" 200 None
add_publisher_urls_resource: DEBUG   :Resetting dropped connection: www.mr.gov.il
add_publisher_urls_resource: DEBUG   :http://www.mr.gov.il:80 "POST /ExemptionMessage/Pages/SearchExemptionMessages.aspx HTTP/1.1" 307 0
add_publisher_urls_resource: DEBUG   :https://www.mr.gov.il:443 "POST /ExemptionMessage/Pages/SearchExemptionMessages.aspx HTTP/1.1" 200 None
add_publisher_urls_resource: DEBUG   :Resetting dropped connection: www.mr.gov.il
add_publisher_urls_resource: DEBUG   :http://www.mr.gov.il:80 "POST /ExemptionMessage/Pages/SearchExemptionMessages.aspx HTTP/1.1" 307 0
add_publisher_urls_resource: DEBUG   :https://www.mr.gov.il:443 "POST /ExemptionMessage/Pages/SearchExemptionMessages.aspx HTTP/1.1" 200 None
add_publisher_urls_resource: DEBUG   :Resetting dropped connection: www.mr.gov.il
add_publisher_urls_resource: DEBUG   :http://www.mr.gov.il:80 "POST /ExemptionMessage/Pages/SearchExemptionMessages.aspx HTTP/1.1" 307 0
add_publisher_urls_resource: DEBUG   :https://www.mr.gov.il:443 "POST /ExemptionMessage/Pages/SearchExemptionMessages.aspx HTTP/1.1" 200 None
add_publisher_urls_resource: DEBUG   :Resetting dropped connection: www.mr.gov.il
add_publisher_urls_resource: DEBUG   :http://www.mr.gov.il:80 "POST /ExemptionMessage/Pages/SearchExemptionMessages.aspx HTTP/1.1" 307 0
```

**Comment by OriHoch** [comment]
@akariv 
> We might be hitting on a limit with the exemption scraping - can you slow down the scraping (make sure requests are throttled)?
> Also note that they’re redirecting everything to https now - going there directly could also reduce the number of requests we’re making.
> once it’s done I can assign tzabar with a new IP

**Comment by OriHoch** [comment]
made some fixes in PR #71

**Comment by OriHoch** [comment]
processors are running after merge.. waiting for them to complete

**Comment by OriHoch** [comment]
:champagne: pipelines ran!

there is a discrepancy in number of rows - I'll investigate that in #76

other then that, data in DB looks good, I think issue can be closed
