### ISSUE TITLE
investigate error in geocode processor: 'result' object has no attribute 'provider'

### ISSUE THREAD

**Issue by OriHoch** [OpenBudget/budgetkey-data-pipelines#75]
```
geocode_entities: INFO    :no update needed: 512206020
geocode_entities: INFO    :no update needed: 512206046
geocode_entities: INFO    :no update needed: 512206079
geocode_entities: INFO    :no update needed: 512206301
geocode_entities: INFO    :no update needed: 512206350
geocode_entities: INFO    :no update needed: 512206384
geocode_entities: Traceback (most recent call last):
geocode_entities:   File "/budgetkey_data_pipelines/pipelines/entities/geocode_entities.py", line 246, in 
geocode_entities:     spew(datapackage, GeoCodeEntities(parameters, datapackage, resources).filter_resources())
geocode_entities:   File "/usr/local/lib/python3.6/site-packages/datapackage_pipelines/wrapper/wrapper.py", line 60, in spew
geocode_entities:     for rec in res:
geocode_entities:   File "/budgetkey_data_pipelines/pipelines/entities/geocode_entities.py", line 202, in filter_resource
geocode_entities:     row = self.get_row(entity_id, entity_location)
geocode_entities:   File "/budgetkey_data_pipelines/pipelines/entities/geocode_entities.py", line 223, in get_row
geocode_entities:     provider, geojson = location_row.provider, location_row.geojson
geocode_entities: AttributeError: 'result' object has no attribute 'provider'
load_sql_table: ERROR   :Output pipe disappeared!
```

**Comment by OriHoch** [comment]
looks like it's due to DB schema changes which weren't done (see #67)
